apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: much-to-do
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9tdWNoX3RvZG9fZGI6MTNtZWw0MTJAY2x1c3RlcjAudzZvcjVoby5tb25nby5tb25nb2RiLm5ldC9tdWNoX3RvZG9fZGI=
  DB_NAME: bXVjaF90b2RvX2Ri
