apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: much-to-do
type: Opaque
data:
  MONGO_URI: mongodb+srv://much_todo_db:13mel412@cluster0.w6or5ho.mongodb.net/much_todo_db
  DB_NAME: much_todo_db
