apiVersion: v1
kind: Secret
metadata:
  name: backend-api-secret
  namespace: much-to-do
type: Opaque
stringData:
  PORT: '8080'

  # --- Database ---
  MONGO_URI: mongodb+srv://much_todo_db:13mel412@cluster0.w6or5ho.mongodb.net/much_todo_db
  DB_NAME: much_todo_db

  # --- Authentication ---
  JWT_SECRET_KEY: 0888c49b192de2fd55314938a83012698cb4d8a631af6f62424d1a05ddb3e7b1
  JWT_EXPIRATION_HOURS: '72'

  # --- Caching (disabled by default) ---
  ENABLE_CACHE: 'false'
